language: node_js

node_js:
  - "node"

os:
- osx

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - git submodule sync && git submodule update --init --recursive

branches:
  only:
    - master
